/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import alertas.MyJOP;
import interfaces.MenuAdministrador;
import seguridad.EncoderA;


/**
 *
 * @author Kevin
 */
public class Administrador extends javax.swing.JPanel
{
    private final String usu = EncoderA.recuperaCred("1");
    private final String pass = EncoderA.recuperaCred("2");
    /**
     * Creates new form citas
     */
    public Administrador()
    {
        initComponents();
        EncoderA.recuperaCred(JTFUsuario, JTFContraseña);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        JTFUsuario = new RSMaterialComponent.RSTextFieldMaterialIcon();
        JTFContraseña = new RSMaterialComponent.RSPasswordMaterialIcon();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tabActivos = new newscomponents.RSButtonIcon_new();
        tabActivos1 = new newscomponents.RSButtonIcon_new();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(26, 117, 159)));

        rSLabelTextIcon1.setForeground(new java.awt.Color(144, 224, 239));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Credenciales del administrador");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);

        JTFUsuario.setForeground(new java.awt.Color(255, 51, 51));
        JTFUsuario.setColorIcon(new java.awt.Color(255, 51, 51));
        JTFUsuario.setColorMaterial(new java.awt.Color(0, 0, 0));
        JTFUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        JTFUsuario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        JTFUsuario.setPhColor(new java.awt.Color(255, 51, 51));
        JTFUsuario.setPlaceholder("Ingrese Usuario");
        JTFUsuario.setSelectionColor(new java.awt.Color(0, 0, 0));
        JTFUsuario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                JTFUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                JTFUsuarioKeyReleased(evt);
            }
        });

        JTFContraseña.setForeground(new java.awt.Color(255, 51, 51));
        JTFContraseña.setColorIcon(new java.awt.Color(255, 51, 51));
        JTFContraseña.setColorMaterial(new java.awt.Color(0, 0, 0));
        JTFContraseña.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        JTFContraseña.setPhColor(new java.awt.Color(255, 51, 51));
        JTFContraseña.setPlaceholder("Ingrese contraseña");
        JTFContraseña.setSelectionColor(new java.awt.Color(0, 0, 0));
        JTFContraseña.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JTFContraseñaActionPerformed(evt);
            }
        });
        JTFContraseña.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                JTFContraseñaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                JTFContraseñaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel2.setText("Contraseña*");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel3.setText("Usuario*");

        tabActivos.setBackground(new java.awt.Color(255, 255, 255));
        tabActivos.setText("Modificar credenciales");
        tabActivos.setBackgroundHover(new java.awt.Color(151, 194, 129));
        tabActivos.setForegroundHover(new java.awt.Color(26, 117, 159));
        tabActivos.setForegroundIcon(new java.awt.Color(233, 196, 106));
        tabActivos.setForegroundText(new java.awt.Color(26, 117, 159));
        tabActivos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS);
        tabActivos.setRound(20);
        tabActivos.setSelected(true);
        tabActivos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tabActivosActionPerformed(evt);
            }
        });

        tabActivos1.setBackground(new java.awt.Color(255, 255, 255));
        tabActivos1.setText("Deshacer cambios");
        tabActivos1.setBackgroundHover(new java.awt.Color(255, 102, 102));
        tabActivos1.setForegroundHover(new java.awt.Color(26, 117, 159));
        tabActivos1.setForegroundIcon(new java.awt.Color(233, 196, 106));
        tabActivos1.setForegroundText(new java.awt.Color(26, 117, 159));
        tabActivos1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SYNC);
        tabActivos1.setRound(20);
        tabActivos1.setSelected(true);
        tabActivos1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tabActivos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(tabActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(tabActivos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabActivos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTFUsuarioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTFUsuarioKeyPressed
    {//GEN-HEADEREND:event_JTFUsuarioKeyPressed
        
    }//GEN-LAST:event_JTFUsuarioKeyPressed

    private void JTFUsuarioKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTFUsuarioKeyReleased
    {//GEN-HEADEREND:event_JTFUsuarioKeyReleased
        
    }//GEN-LAST:event_JTFUsuarioKeyReleased

    private void JTFContraseñaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JTFContraseñaActionPerformed
    {//GEN-HEADEREND:event_JTFContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFContraseñaActionPerformed

    private void JTFContraseñaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTFContraseñaKeyPressed
    {//GEN-HEADEREND:event_JTFContraseñaKeyPressed
       
    }//GEN-LAST:event_JTFContraseñaKeyPressed

    private void JTFContraseñaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTFContraseñaKeyReleased
    {//GEN-HEADEREND:event_JTFContraseñaKeyReleased
        
    }//GEN-LAST:event_JTFContraseñaKeyReleased

    private void tabActivosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tabActivosActionPerformed
    {//GEN-HEADEREND:event_tabActivosActionPerformed
        if (MyJOP.myJOPShowConfirmDialog(null, "Esta seguro de editar las creedenciales")==1)
        {
            EncoderA.reasignaCred(JTFUsuario.getText().trim(), JTFContraseña.getText().trim());
            EncoderA.recuperaCred(JTFUsuario, JTFContraseña);
            MyJOP.myJOPShowMessageDialog(null, "Se cerrara la sesión actual");
            MenuAdministrador.cerrar();
        } 
    }//GEN-LAST:event_tabActivosActionPerformed

    private void tabActivos1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tabActivos1ActionPerformed
    {//GEN-HEADEREND:event_tabActivos1ActionPerformed
        JTFUsuario.setText(usu);
        JTFContraseña.setText(pass);
    }//GEN-LAST:event_tabActivos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSPasswordMaterialIcon JTFContraseña;
    private RSMaterialComponent.RSTextFieldMaterialIcon JTFUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private static newscomponents.RSButtonIcon_new tabActivos;
    private static newscomponents.RSButtonIcon_new tabActivos1;
    // End of variables declaration//GEN-END:variables
}
