/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author Kevin
 */
public class Inicio extends javax.swing.JPanel
{

    /**
     * Creates new form Inicio
     */
    public Inicio()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        labelIcon1 = new necesario.LabelIcon();
        cantiProximas = new javax.swing.JLabel();
        ProgressProximas = new rojerusan.componentes.RSProgressBarSinText();
        lbNumeroP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PorcentajeProximas = new javax.swing.JLabel();
        rSPanelBorder5 = new RSMaterialComponent.RSPanelBorder();
        labelIcon5 = new necesario.LabelIcon();
        jLabel5 = new javax.swing.JLabel();
        ProgressCanceladas = new rojerusan.componentes.RSProgressBarSinText();
        lbNumeroC = new javax.swing.JLabel();
        cantiCanceladas = new javax.swing.JLabel();
        PorcentajeCanceladas = new javax.swing.JLabel();
        rSPanelBorder6 = new RSMaterialComponent.RSPanelBorder();
        labelIcon6 = new necesario.LabelIcon();
        jLabel6 = new javax.swing.JLabel();
        ProgressAtentidas = new rojerusan.componentes.RSProgressBarSinText();
        lbNumeroA = new javax.swing.JLabel();
        cantiAtendidas = new javax.swing.JLabel();
        PorcentajeAtendidas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(204, 182, 128));
        rSPanelBorder1.setRound(10);

        labelIcon1.setBackground(new java.awt.Color(255, 255, 255));
        labelIcon1.setForeground(new java.awt.Color(204, 182, 128));
        labelIcon1.setToolTipText("");
        labelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCESS_TIME);
        labelIcon1.setRound(10);

        cantiProximas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cantiProximas.setForeground(new java.awt.Color(204, 182, 128));
        cantiProximas.setText("2/10");

        ProgressProximas.setForeground(new java.awt.Color(204, 182, 128));
        ProgressProximas.setColorBorde(new java.awt.Color(204, 182, 128));
        ProgressProximas.setColorForeground(new java.awt.Color(204, 182, 128));
        ProgressProximas.setGrosorBorde(5);

        lbNumeroP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNumeroP.setForeground(new java.awt.Color(204, 182, 128));
        lbNumeroP.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 182, 128));
        jLabel2.setText("Citas Proximas");

        PorcentajeProximas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PorcentajeProximas.setForeground(new java.awt.Color(204, 182, 128));
        PorcentajeProximas.setText("20%");

        javax.swing.GroupLayout rSPanelBorder1Layout = new javax.swing.GroupLayout(rSPanelBorder1);
        rSPanelBorder1.setLayout(rSPanelBorder1Layout);
        rSPanelBorder1Layout.setHorizontalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgressProximas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addComponent(cantiProximas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PorcentajeProximas))
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addComponent(labelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNumeroP, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        rSPanelBorder1Layout.setVerticalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNumeroP)))
                .addGap(18, 18, 18)
                .addComponent(ProgressProximas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantiProximas)
                    .addComponent(PorcentajeProximas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelBorder5.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder5.setBgBorder(new java.awt.Color(255, 51, 51));
        rSPanelBorder5.setRound(10);

        labelIcon5.setBackground(new java.awt.Color(255, 255, 255));
        labelIcon5.setForeground(new java.awt.Color(255, 51, 51));
        labelIcon5.setToolTipText("");
        labelIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE_CIRCLE);
        labelIcon5.setRound(10);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Citas Canceladas");

        ProgressCanceladas.setForeground(new java.awt.Color(255, 51, 51));
        ProgressCanceladas.setColorBorde(new java.awt.Color(255, 51, 51));
        ProgressCanceladas.setColorForeground(new java.awt.Color(255, 51, 51));
        ProgressCanceladas.setGrosorBorde(5);

        lbNumeroC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNumeroC.setForeground(new java.awt.Color(255, 51, 51));
        lbNumeroC.setText("0");

        cantiCanceladas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cantiCanceladas.setForeground(new java.awt.Color(255, 51, 51));
        cantiCanceladas.setText("1/10");

        PorcentajeCanceladas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PorcentajeCanceladas.setForeground(new java.awt.Color(255, 51, 51));
        PorcentajeCanceladas.setText("10%");

        javax.swing.GroupLayout rSPanelBorder5Layout = new javax.swing.GroupLayout(rSPanelBorder5);
        rSPanelBorder5.setLayout(rSPanelBorder5Layout);
        rSPanelBorder5Layout.setHorizontalGroup(
            rSPanelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgressCanceladas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rSPanelBorder5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelBorder5Layout.createSequentialGroup()
                        .addComponent(cantiCanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PorcentajeCanceladas))
                    .addGroup(rSPanelBorder5Layout.createSequentialGroup()
                        .addComponent(labelIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rSPanelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(lbNumeroC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))))
                .addContainerGap())
        );
        rSPanelBorder5Layout.setVerticalGroup(
            rSPanelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelBorder5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(lbNumeroC)))
                .addGap(18, 18, 18)
                .addComponent(ProgressCanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantiCanceladas)
                    .addComponent(PorcentajeCanceladas))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        rSPanelBorder6.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder6.setBgBorder(new java.awt.Color(51, 153, 0));
        rSPanelBorder6.setRound(10);

        labelIcon6.setBackground(new java.awt.Color(255, 255, 255));
        labelIcon6.setForeground(new java.awt.Color(51, 153, 0));
        labelIcon6.setToolTipText("");
        labelIcon6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK_BOX);
        labelIcon6.setRound(10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("Citas Atendidas");

        ProgressAtentidas.setForeground(new java.awt.Color(51, 153, 0));
        ProgressAtentidas.setColorBorde(new java.awt.Color(51, 153, 0));
        ProgressAtentidas.setColorForeground(new java.awt.Color(51, 153, 0));
        ProgressAtentidas.setGrosorBorde(5);

        lbNumeroA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNumeroA.setForeground(new java.awt.Color(51, 153, 0));
        lbNumeroA.setText("0");

        cantiAtendidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cantiAtendidas.setForeground(new java.awt.Color(51, 153, 0));
        cantiAtendidas.setText("3/10");

        PorcentajeAtendidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PorcentajeAtendidas.setForeground(new java.awt.Color(51, 153, 0));
        PorcentajeAtendidas.setText("30%");

        javax.swing.GroupLayout rSPanelBorder6Layout = new javax.swing.GroupLayout(rSPanelBorder6);
        rSPanelBorder6.setLayout(rSPanelBorder6Layout);
        rSPanelBorder6Layout.setHorizontalGroup(
            rSPanelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgressAtentidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rSPanelBorder6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelBorder6Layout.createSequentialGroup()
                        .addComponent(cantiAtendidas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PorcentajeAtendidas))
                    .addGroup(rSPanelBorder6Layout.createSequentialGroup()
                        .addComponent(labelIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rSPanelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(lbNumeroA, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))))
                .addContainerGap())
        );
        rSPanelBorder6Layout.setVerticalGroup(
            rSPanelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelBorder6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(lbNumeroA)))
                .addGap(18, 18, 18)
                .addComponent(ProgressAtentidas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantiAtendidas)
                    .addComponent(PorcentajeAtendidas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPanelBorder6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPanelBorder5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSPanelBorder5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelBorder6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(435, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PorcentajeAtendidas;
    private javax.swing.JLabel PorcentajeCanceladas;
    private javax.swing.JLabel PorcentajeProximas;
    private rojerusan.componentes.RSProgressBarSinText ProgressAtentidas;
    private rojerusan.componentes.RSProgressBarSinText ProgressCanceladas;
    private rojerusan.componentes.RSProgressBarSinText ProgressProximas;
    private javax.swing.JLabel cantiAtendidas;
    private javax.swing.JLabel cantiCanceladas;
    private javax.swing.JLabel cantiProximas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private necesario.LabelIcon labelIcon1;
    private necesario.LabelIcon labelIcon3;
    private necesario.LabelIcon labelIcon4;
    private necesario.LabelIcon labelIcon5;
    private necesario.LabelIcon labelIcon6;
    private javax.swing.JLabel lbNumeroA;
    private javax.swing.JLabel lbNumeroC;
    private javax.swing.JLabel lbNumeroP;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder3;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder4;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder5;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder6;
    // End of variables declaration//GEN-END:variables
}
