/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import RSMaterialComponent.RSTableMetroCustom;
import java.awt.Color;
import javax.swing.table.TableColumn;
import metodosAux.MetodosAux;
import metodosAux.RSButtonsAction;
import metodosAux.RSButtonsRenderer;
import metodosAux.SysConfigs;
import metodosBD.MetodosBD;
import rojeru_san.efectos.ValoresEnum;

/**
 *
 * @author Kevin
 */
public class TablaContenidoCitas extends javax.swing.JPanel
{

    /**
     * Creates new form tablaContenidoCitas
     */
    public TablaContenidoCitas()
    {
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        
    }
    
    /**
     * Método encargado de mostrar graficamente los datos de los pacientes
     * dentro de la tabla correspondiente
     *
     * @param tabla tabla de pacientes
     * @param tab categoria seleccionada
     * @param filtro Nombre de un paciente en especifico (Para busqueda filtrada
     * y puede ser null)
     */
    public static void listarPacientes(RSTableMetroCustom tabla, int tab, String filtro)
    {
        if (filtro == null)
        {
            filtro = "";
        }
        String[] columnas =
        {
            "id", "accion", "nombrePaciente", "fecha", "hora", "usuarioAtiende", "estatusCitasId", "fechaRegistro", "usuarioEdito"
        };
        MetodosAux.listarTablas(MetodosBD.rsListarCitas(tab, filtro), tabla, columnas);

        //Definimos la posicion donde estara la columna que contendra los botones
        TableColumn column = tabla.getColumnModel().getColumn(1);
        column.setCellRenderer(new RSButtonsRenderer());
        String classname = "paneles.TablaContenidoPacientes";
        String metodoVer = "viewInfo";
        String metodoEditar = "editInfo";
        Object[] params =
        {
            classname, metodoVer, metodoEditar
        };
        //El 0 de aqui es de donde agarrara el parametro para activar los botones
        column.setCellEditor(new RSButtonsAction(tabla, 0, params));
    }
    
    /**
     * Metodo que actualiza el titulo que se depliega en la parte inferior
     * dependiendo del tab que se seleccione
     *
     * @param tab tab seleccionado
     */
    public static void actualizarTitulo(int tab)
    {
        switch (tab)
        {
            case 1:
                TituloActual.setText("Citas Próximas");
                TituloActual.setForeground(SysConfigs.cl_proximas);
                TituloActual.setIcons(ValoresEnum.ICONS.ACCESS_TIME);
                break;
            case 2:
                TituloActual.setText("Citas Atendidas");
                TituloActual.setForeground(SysConfigs.cl_activos);
                TituloActual.setIcons(ValoresEnum.ICONS.CHECK_BOX);
                break;
            case 3:
                TituloActual.setText("Citas Canceladas");
                TituloActual.setForeground(SysConfigs.cl_inactivos);
                TituloActual.setIcons(ValoresEnum.ICONS.REMOVE_CIRCLE);
                break;
            case 0:
                TituloActual.setText("Todas atendias");
                TituloActual.setForeground(SysConfigs.cl_todos);
                TituloActual.setIcons(ValoresEnum.ICONS.REORDER);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new RSMaterialComponent.RSTableMetroCustom();
        TituloActual = new RSMaterialComponent.RSLabelTextIcon();
        rSTextFieldMaterialIcon1 = new RSMaterialComponent.RSTextFieldMaterialIcon();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Id", "Cliente", "Fecha Cita", "Fecha Hora", "Atiende"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblCitas.setBackgoundHead(new java.awt.Color(26, 117, 159));
        tblCitas.setBackgoundHover(new java.awt.Color(26, 117, 159));
        tblCitas.setColorPrimaryText(new java.awt.Color(26, 117, 159));
        tblCitas.setColorSecondary(new java.awt.Color(255, 255, 255));
        tblCitas.setColorSecundaryText(new java.awt.Color(26, 117, 159));
        tblCitas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setFontHead(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblCitas.setFontRowHover(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setFontRowSelect(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setSelectionBackground(new java.awt.Color(26, 117, 159));
        jScrollPane1.setViewportView(tblCitas);

        TituloActual.setForeground(new java.awt.Color(233, 196, 106));
        TituloActual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TituloActual.setText("Citas próximas");
        TituloActual.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCESS_TIME);
        TituloActual.setSizeIcon(30.0F);

        rSTextFieldMaterialIcon1.setForeground(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setColorIcon(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setColorMaterial(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        rSTextFieldMaterialIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldMaterialIcon1.setPhColor(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setPlaceholder("Buscar cita");
        rSTextFieldMaterialIcon1.setSelectionColor(new java.awt.Color(26, 117, 159));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TituloActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                        .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static RSMaterialComponent.RSLabelTextIcon TituloActual;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon1;
    private RSMaterialComponent.RSTableMetroCustom tblCitas;
    // End of variables declaration//GEN-END:variables
}
