/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author Kevin
 */
public class TablaContenidoPacientes extends javax.swing.JPanel
{

    /**
     * Creates new form tablaContenidoCitas
     */
    public TablaContenidoPacientes()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new RSMaterialComponent.RSTableMetroCustom();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSTextFieldMaterialIcon1 = new RSMaterialComponent.RSTextFieldMaterialIcon();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String []
            {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Sexo", "Teléfono", "Correo"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblCitas.setBackgoundHead(new java.awt.Color(26, 117, 159));
        tblCitas.setBackgoundHover(new java.awt.Color(26, 117, 159));
        tblCitas.setColorPrimaryText(new java.awt.Color(26, 117, 159));
        tblCitas.setColorSecondary(new java.awt.Color(255, 255, 255));
        tblCitas.setColorSecundaryText(new java.awt.Color(26, 117, 159));
        tblCitas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setFontHead(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblCitas.setFontRowHover(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setFontRowSelect(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setSelectionBackground(new java.awt.Color(26, 117, 159));
        jScrollPane1.setViewportView(tblCitas);

        rSLabelTextIcon1.setForeground(new java.awt.Color(51, 153, 0));
        rSLabelTextIcon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon1.setText("Pacientes Activos");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        rSLabelTextIcon1.setSizeIcon(30.0F);

        rSTextFieldMaterialIcon1.setForeground(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setText("Buscar Paciente");
        rSTextFieldMaterialIcon1.setColorIcon(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setColorMaterial(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        rSTextFieldMaterialIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldMaterialIcon1.setPhColor(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.setPlaceholder("Buscar cita");
        rSTextFieldMaterialIcon1.setSelectionColor(new java.awt.Color(26, 117, 159));
        rSTextFieldMaterialIcon1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSTextFieldMaterialIcon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                        .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTextFieldMaterialIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSTextFieldMaterialIcon1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSTextFieldMaterialIcon1ActionPerformed
    {//GEN-HEADEREND:event_rSTextFieldMaterialIcon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterialIcon1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon1;
    private RSMaterialComponent.RSTableMetroCustom tblCitas;
    // End of variables declaration//GEN-END:variables
}
