/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import RSMaterialComponent.RSTableMetroCustom;
import java.awt.Color;
import metodosAux.SysConfigs;
import metodosAux.MetodosAux;
import metodosBD.MetodosBD;

/**
 *
 * @author Kevin
 */
public class TablaContenidoPacientes extends javax.swing.JPanel
{
    /**
     * Creates new form tablaContenidoCitas
     */
    public TablaContenidoPacientes()
    {
        initComponents();
        listarPacientes(tblCitas, 1, jTBuscarPaciente.getText().trim());
        jScrollPane1.getViewport().setBackground(Color.WHITE);
    }

    /**
     * Método encargado de mostrar graficamente los datos de los pacientes dentro de la tabla correspondiente
     * @param tabla tabla de pacientes
     * @param tab categoria seleccionada
     * @param filtro Nombre de un paciente en especifico (Para busqueda filtrada y puede ser null)
     */
    public static void listarPacientes(RSTableMetroCustom tabla, int tab, String filtro)
    {
        if (filtro == null)
        {
            filtro = "";
        }
        String[] columnas =
        {
            "nombre", "apellidoPaterno", "apellidoMaterno", "sexo", "telefono", "correo","estatusPac"
        };
        MetodosAux.listarTablas(MetodosBD.rsListarPacientes(tab, filtro), tabla, columnas);
    }
    
    /**
     * M;etodo que actualiza el titulo que se depliega en la parte inferior dependiendo del tab que se seleccione
     * @param tab tab seleccionado
     */
    public static void actualizarTitulo(int tab)
    {
        switch (tab)
        {
            case 1:
               JLTitulo.setText("Clientes Activos");
               JLTitulo.setForeground(SysConfigs.cl_activos);
                break;
            case 2:
                JLTitulo.setText("Clientes Inactivos");
               JLTitulo.setForeground(SysConfigs.cl_inactivos);
                break;
            case 0:
                JLTitulo.setText("Todos los Clientes");
               JLTitulo.setForeground(SysConfigs.cl_todos);
                break;
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new RSMaterialComponent.RSTableMetroCustom();
        JLTitulo = new RSMaterialComponent.RSLabelTextIcon();
        jTBuscarPaciente = new RSMaterialComponent.RSTextFieldMaterialIcon();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Sexo", "Teléfono", "Correo", "Estatus"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblCitas.setBackgoundHead(new java.awt.Color(26, 117, 159));
        tblCitas.setBackgoundHover(new java.awt.Color(26, 117, 159));
        tblCitas.setColorPrimaryText(new java.awt.Color(26, 117, 159));
        tblCitas.setColorSecondary(new java.awt.Color(255, 255, 255));
        tblCitas.setColorSecundaryText(new java.awt.Color(26, 117, 159));
        tblCitas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setFontHead(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblCitas.setFontRowHover(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setFontRowSelect(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblCitas.setSelectionBackground(new java.awt.Color(26, 117, 159));
        jScrollPane1.setViewportView(tblCitas);

        JLTitulo.setForeground(new java.awt.Color(51, 153, 0));
        JLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLTitulo.setText("Pacientes Activos");
        JLTitulo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        JLTitulo.setSizeIcon(30.0F);

        jTBuscarPaciente.setForeground(new java.awt.Color(26, 117, 159));
        jTBuscarPaciente.setColorIcon(new java.awt.Color(26, 117, 159));
        jTBuscarPaciente.setColorMaterial(new java.awt.Color(26, 117, 159));
        jTBuscarPaciente.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTBuscarPaciente.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jTBuscarPaciente.setPhColor(new java.awt.Color(26, 117, 159));
        jTBuscarPaciente.setPlaceholder("Buscar paciente");
        jTBuscarPaciente.setSelectionColor(new java.awt.Color(26, 117, 159));
        jTBuscarPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTBuscarPacienteActionPerformed(evt);
            }
        });
        jTBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTBuscarPacienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                        .addComponent(jTBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTBuscarPacienteActionPerformed
    {//GEN-HEADEREND:event_jTBuscarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarPacienteActionPerformed

    private void jTBuscarPacienteKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTBuscarPacienteKeyReleased
    {//GEN-HEADEREND:event_jTBuscarPacienteKeyReleased
        System.out.println(jTBuscarPaciente.getText().trim());
        listarPacientes(tblCitas, Pacientes.tabSelecc, jTBuscarPaciente.getText().trim());

    }//GEN-LAST:event_jTBuscarPacienteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static RSMaterialComponent.RSLabelTextIcon JLTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSTextFieldMaterialIcon jTBuscarPaciente;
    public RSMaterialComponent.RSTableMetroCustom tblCitas;
    // End of variables declaration//GEN-END:variables
}
