/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import RSMaterialComponent.RSTableMetroCustom;
import formularios_Detalles.InfoPacientes;
import formularios_Ediciones.EditPacientes;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import metodosAux.SysConfigs;
import metodosAux.MetodosAux;
import metodosAux.RSButtonsAction;
import metodosAux.RSButtonsRenderer;
import metodosBD.MetodosBD;

/**
 *
 * @author Kevin
 */
public class TablaContenidoUsuarios extends javax.swing.JPanel
{

    /**
     * Creates new form tablaContenidoCitas
     */
    public TablaContenidoUsuarios()
    {
        initComponents();
        listarUsuarios(tblUsuario, 1, jTBuscarUsuario.getText().trim());
        jScrollPane1.getViewport().setBackground(Color.WHITE);
    }

    /**
     * Método encargado de mostrar graficamente los datos de los pacientes
     * dentro de la tabla correspondiente
     *
     * @param tabla tabla de pacientes
     * @param tab categoria seleccionada
     * @param filtro Nombre de un paciente en especifico (Para busqueda filtrada
     * y puede ser null)
     */
    public static void listarUsuarios(RSTableMetroCustom tabla, int tab, String filtro)
    {
        if (filtro == null)
        {
            filtro = "";
        }
        String[] columnas =
        {
            "id", "accion", "usuario" ,"nombre", "apellidoPaterno", "apellidoMaterno", "estatusUsr", "sexo"
        };
        MetodosAux.listarTablas(MetodosBD.rsListarUsuarios(tab, filtro), tabla, columnas);

        //Definimos la posicion donde estara la columna que contendra los botones
        TableColumn column = tabla.getColumnModel().getColumn(1);
        column.setCellRenderer(new RSButtonsRenderer());
        String classname = "paneles.TablaContenidoUsuarios";
        String metodoVer = "viewInfo";
        String metodoEditar = "editInfo";
        Object[] params =
        {
            classname, metodoVer, metodoEditar
        };
        //El 0 de aqui es de donde agarrara el parametro para activar los botones
        column.setCellEditor(new RSButtonsAction(tabla, 0, params));
    }

    /**
     * M;etodo que actualiza el titulo que se depliega en la parte inferior
     * dependiendo del tab que se seleccione
     *
     * @param tab tab seleccionado
     */
    public static void actualizarTitulo(int tab)
    {
        switch (tab)
        {
            case 1:
                JLTitulo.setText("Usuarios Activos");
                JLTitulo.setForeground(SysConfigs.cl_activos);
                break;
            case 2:
                JLTitulo.setText("Usuarios Inactivos");
                JLTitulo.setForeground(SysConfigs.cl_inactivos);
                break;
            case 0:
                JLTitulo.setText("Todos los Usuarios");
                JLTitulo.setForeground(SysConfigs.cl_todos);
                break;

        }
    }

    public void viewInfo(Object value)
    {
        new InfoPacientes(null, true, MetodosBD.getPaciente(value.toString())).setVisible(true);
    }

    public void editInfo(Object value)
    {
        new EditPacientes(MetodosBD.getPaciente(value.toString())).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new RSMaterialComponent.RSTableMetroCustom();
        JLTitulo = new RSMaterialComponent.RSLabelTextIcon();
        jTBuscarUsuario = new RSMaterialComponent.RSTextFieldMaterialIcon();

        setBackground(new java.awt.Color(255, 255, 255));

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "id", "Accion", "Usuario", "Nombre", "Apellido Paterno", "Apellido Materno", "Estatus", "Sexo"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblUsuario.setBackgoundHead(new java.awt.Color(26, 117, 159));
        tblUsuario.setBackgoundHover(new java.awt.Color(26, 117, 159));
        tblUsuario.setBorderRows(null);
        tblUsuario.setColorPrimaryText(new java.awt.Color(26, 117, 159));
        tblUsuario.setColorSecondary(new java.awt.Color(255, 255, 255));
        tblUsuario.setColorSecundaryText(new java.awt.Color(26, 117, 159));
        tblUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        tblUsuario.setFontHead(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblUsuario.setFontRowHover(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        tblUsuario.setFontRowSelect(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        tblUsuario.setHighHead(40);
        tblUsuario.setRowHeight(35);
        tblUsuario.setSelectionBackground(new java.awt.Color(26, 117, 159));
        jScrollPane1.setViewportView(tblUsuario);
        if (tblUsuario.getColumnModel().getColumnCount() > 0)
        {
            tblUsuario.getColumnModel().getColumn(0).setMinWidth(0);
            tblUsuario.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblUsuario.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        JLTitulo.setForeground(new java.awt.Color(51, 153, 0));
        JLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLTitulo.setText("Usuarios Activos");
        JLTitulo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        JLTitulo.setSizeIcon(30.0F);

        jTBuscarUsuario.setForeground(new java.awt.Color(26, 117, 159));
        jTBuscarUsuario.setToolTipText("Buscar por nombre o apellido paterno");
        jTBuscarUsuario.setColorIcon(new java.awt.Color(26, 117, 159));
        jTBuscarUsuario.setColorMaterial(new java.awt.Color(26, 117, 159));
        jTBuscarUsuario.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTBuscarUsuario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jTBuscarUsuario.setPhColor(new java.awt.Color(26, 117, 159));
        jTBuscarUsuario.setPlaceholder("Buscar usuario");
        jTBuscarUsuario.setSelectionColor(new java.awt.Color(26, 117, 159));
        jTBuscarUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTBuscarUsuarioActionPerformed(evt);
            }
        });
        jTBuscarUsuario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTBuscarUsuarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                        .addComponent(jTBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTBuscarUsuarioActionPerformed
    {//GEN-HEADEREND:event_jTBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarUsuarioActionPerformed

    private void jTBuscarUsuarioKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTBuscarUsuarioKeyReleased
    {//GEN-HEADEREND:event_jTBuscarUsuarioKeyReleased
        System.out.println(jTBuscarUsuario.getText().trim());
        listarUsuarios(tblUsuario, Pacientes.tabSelecc, jTBuscarUsuario.getText().trim());
    }//GEN-LAST:event_jTBuscarUsuarioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static RSMaterialComponent.RSLabelTextIcon JLTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSTextFieldMaterialIcon jTBuscarUsuario;
    public static RSMaterialComponent.RSTableMetroCustom tblUsuario;
    // End of variables declaration//GEN-END:variables
}
