/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_Ediciones;

import RSMaterialComponent.RSTextFieldOne;
import alertas.MyJOP;
import interfaces.MenuUsuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import rojeru_san.complementos.RSUtilities;
import metodosAux.*;
import metodosBD.MetodosBD;
import paneles.Pacientes;
import static paneles.Pacientes.tablaContenidoPacientes2;
import paneles.Servicios;
import static paneles.Servicios.tabSelecc;
import static paneles.Servicios.tablaContenidoServicios1;
import paneles.TablaContenidoPacientes;
import paneles.TablaContenidoServicios;

/**
 *
 * @author David Vergara
 */
public class EditServicios extends javax.swing.JDialog
{

    /**
     * Creates new form FormPacientes
     */
    int id;

    //False campos requeridos, true campos no requeridos
    boolean descripcionC = true;
    boolean nombreC = true;

    public EditServicios(RSObjectArray datos)
    {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(pnlFondo, 150);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);
        iniCampos();
        RSTextFieldOne rs[] =
        {
            nombre
        };
        Validaciones.disableCP(rs);

        //Insertamos los datos que se tienen en la base de datos dentro de los campos
        id = Integer.parseInt(datos.getValue("id").toString());
        nombre.setText((String) datos.getValue("nombreServ"));
        descripcion.setText((String) datos.getValue("descripcion"));
    }

    public EditServicios()
    {

    }

    /**
     * Método encargado de incializar los campos del formulario y los coloca por
     * default
     */
    public void iniCampos()
    {
        this.error_nombre.setForeground(Color.white);
        this.error_descripcion.setForeground(Color.white);
        this.nombre.setText(null);
        this.descripcion.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlFondo = new javax.swing.JPanel();
        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        rSPanelBorderGradient1 = new RSMaterialComponent.RSPanelBorderGradient();
        btnCerrar = new RSMaterialComponent.RSButtonIconOne();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new newscomponents.RSButtonIcon_new();
        jLabel2 = new javax.swing.JLabel();
        nombre = new RSMaterialComponent.RSTextFieldOne();
        error_nombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        error_descripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlFondo.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(26, 117, 159));
        rSPanelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelBorderGradient1.setBgShade(new java.awt.Color(26, 117, 159));
        rSPanelBorderGradient1.setColorPrimario(new java.awt.Color(26, 117, 159));
        rSPanelBorderGradient1.setColorSecundario(new java.awt.Color(160, 187, 200));
        rSPanelBorderGradient1.setGradiente(RSMaterialComponent.RSPanelBorderGradient.Gradiente.CIRCULAR);

        btnCerrar.setBackground(new java.awt.Color(216, 43, 43));
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setBackgroundHover(new java.awt.Color(255, 51, 51));
        btnCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCerrar.setRound(50);
        btnCerrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar datos del servicio");

        javax.swing.GroupLayout rSPanelBorderGradient1Layout = new javax.swing.GroupLayout(rSPanelBorderGradient1);
        rSPanelBorderGradient1.setLayout(rSPanelBorderGradient1Layout);
        rSPanelBorderGradient1Layout.setHorizontalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rSPanelBorderGradient1Layout.setVerticalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addGroup(rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        rSPanelBorder1.add(rSPanelBorderGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        btnRegistrar.setBackground(new java.awt.Color(26, 117, 159));
        btnRegistrar.setText("Guardar cambios");
        btnRegistrar.setBackgroundHover(new java.awt.Color(129, 161, 176));
        btnRegistrar.setEnabled(false);
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);
        btnRegistrar.setRound(20);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel2.setText("Nombre*");
        rSPanelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 300, -1));

        nombre.setForeground(new java.awt.Color(51, 51, 51));
        nombre.setBorderColor(new java.awt.Color(51, 51, 51));
        nombre.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nombre.setPhColor(new java.awt.Color(51, 51, 51));
        nombre.setPlaceholder("Nombre");
        nombre.setSelectionColor(new java.awt.Color(51, 51, 51));
        nombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreKeyTyped(evt);
            }
        });
        rSPanelBorder1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 400, -1));

        error_nombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        error_nombre.setText("Etiqueta de Error");
        rSPanelBorder1.add(error_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 290, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel5.setText("Descripción*");
        rSPanelBorder1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        descripcion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                descripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                descripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(descripcion);

        rSPanelBorder1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 500, -1));

        error_descripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        error_descripcion.setText("Etiqueta de Error");
        rSPanelBorder1.add(error_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 330, -1));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarActionPerformed

        if (nombreC && descripcionC)
        {
            Object[] datosUpdate =
            {
                //Mandamos la informacion que puede contener vacio segun lo que se tenga almacenado en la caja de texto
                nombre.getText().trim(), descripcion.getText().trim(), MenuUsuario.idUsuario,
                MetodosAux.getFecha()
            };
            if (MyJOP.myJOPShowConfirmDialog(null, "¿Estas seguro que deseas realizar esta acción?") == 1)
            {
                boolean insercionCorr = MetodosBD.actualizarServicio(id, datosUpdate);
                if (insercionCorr)
                {
                    MetodosAux.mostrarAlerta("Muy bien hecho", "Se han actualizado con exito los datos del servicio", 1);
                    dispose();
                    //Borramos la ruta de la imagen para refrescar
                    //Actualizamos los usuariosd de las tablas
                    TablaContenidoServicios.listarServicios(tablaContenidoServicios1.tblServicios, tabSelecc, null);
                    //Actualizamos el contador
                    Servicios.actualizarNumServicios();
                } else
                {
                    MetodosAux.mostrarAlerta("Error", " Ha ocurrido un error al actualizar los datos del servicio", 2);
                }
            }
            dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarActionPerformed
    {//GEN-HEADEREND:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void nombreKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyReleased
    {//GEN-HEADEREND:event_nombreKeyReleased
        nombreC = MetodosAux.validarFormu(nombre, error_nombre, "required");
        if (nombre.getText().length() <= 2 && !nombre.getText().isEmpty())
        {
            error_nombre.setForeground(SysConfigs.bg_warning);
            error_nombre.setText("Digite mas de 2 digitos");
            nombreC = false;
        }
        btnRegistrar.setEnabled((descripcionC == true && nombreC == true) ? true : false);
    }//GEN-LAST:event_nombreKeyReleased

    private void nombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyTyped
    {//GEN-HEADEREND:event_nombreKeyTyped
        if (nombre.getText().length() >= 25)
        {
            evt.consume();
        }
        setTransferHandler(null);
        Validaciones.entradaLetrasNum(evt, 1);
    }//GEN-LAST:event_nombreKeyTyped

    private void descripcionKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_descripcionKeyReleased
    {//GEN-HEADEREND:event_descripcionKeyReleased
        descripcionC = MetodosAux.validarFormuText(descripcion, error_descripcion, "required");
        if (descripcion.getText().length() <= 2 && !descripcion.getText().isEmpty())
        {
            error_descripcion.setForeground(SysConfigs.bg_warning);
            error_descripcion.setText("Descripcion muy corta");
            descripcionC = false;
        }
        btnRegistrar.setEnabled((descripcionC == true && nombreC == true) ? true : false);
    }//GEN-LAST:event_descripcionKeyReleased

    private void descripcionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_descripcionKeyTyped
    {//GEN-HEADEREND:event_descripcionKeyTyped
        if (descripcion.getText().length() >= 200)
        {
            evt.consume();
        }
        setTransferHandler(null);
    }//GEN-LAST:event_descripcionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(EditServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(EditServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(EditServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(EditServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new EditServicios().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnCerrar;
    private newscomponents.RSButtonIcon_new btnRegistrar;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel error_descripcion;
    private javax.swing.JLabel error_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSTextFieldOne nombre;
    private javax.swing.JPanel pnlFondo;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient1;
    // End of variables declaration//GEN-END:variables
}
