/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_Registros;

import RSMaterialComponent.RSTextFieldOne;
import alertas.Alerta;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import rojeru_san.complementos.RSUtilities;
import metodosAux.*;
import metodosBD.MetodosBD;
import paneles.Pacientes;
import static paneles.Pacientes.tabSelecc;
import static paneles.Pacientes.tablaContenidoPacientes2;
import paneles.TablaContenidoPacientes;
import paneles.TablaContenidoUsuarios;
import paneles.Usuarios;
import seguridad.Encoder;
import static paneles.Usuarios.tablaContenidoUsuarios2;

/**
 *
 * @author David Vergara
 */
public class RegMedicos extends javax.swing.JDialog
{

    /**
     * Creates new form FormPacientes
     */
    String rutaImgPerfil = "";

    //False campos requeridos, true campos no requerido
    boolean nombreC = false;
    boolean apeP = false;
    boolean apeM = true;
    boolean curpC = false;

    public RegMedicos()
    {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(pnlFondo, 150);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);
        iniCampos();
        RSTextFieldOne rs[] =
        {
            nombre, apellidoMaterno, apellidoPaterno, CURP
        };
        Validaciones.disableCP(rs);
    }

    /**
     * Método encargado de incializar los campos del formulario y los coloca por
     * default
     */
    public void iniCampos()
    {
        this.error_nombre.setForeground(Color.white);
        this.error_apellidoPaterno.setForeground(Color.white);
        this.error_apellidoMaterno.setForeground(Color.white);
        this.error_sexo.setForeground(Color.white);
        this.error_usuario.setForeground(Color.white);
        this.nombre.setText(null);
        this.apellidoPaterno.setText(null);
        this.apellidoMaterno.setText(null);
        this.sexo.setSelectedIndex(0);
        this.CURP.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlFondo = new javax.swing.JPanel();
        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        btnOpenFoto = new RSMaterialComponent.RSButtonIconOne();
        lblFoto = new RSMaterialComponent.RSPanelBorderImage();
        rSPanelBorderGradient1 = new RSMaterialComponent.RSPanelBorderGradient();
        btnCerrar = new RSMaterialComponent.RSButtonIconOne();
        jLabel1 = new javax.swing.JLabel();
        btnRemove = new RSMaterialComponent.RSButtonIconOne();
        nombre = new RSMaterialComponent.RSTextFieldOne();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        apellidoPaterno = new RSMaterialComponent.RSTextFieldOne();
        jLabel5 = new javax.swing.JLabel();
        apellidoMaterno = new RSMaterialComponent.RSTextFieldOne();
        jLabel8 = new javax.swing.JLabel();
        sexo = new RSMaterialComponent.RSComboBox();
        jLabel7 = new javax.swing.JLabel();
        CURP = new RSMaterialComponent.RSTextFieldOne();
        btnRegistrar = new newscomponents.RSButtonIcon_new();
        error_nombre = new javax.swing.JLabel();
        error_apellidoPaterno = new javax.swing.JLabel();
        error_sexo = new javax.swing.JLabel();
        error_usuario = new javax.swing.JLabel();
        error_apellidoMaterno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlFondo.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(68, 165, 160));
        rSPanelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenFoto.setBackground(new java.awt.Color(68, 165, 160));
        btnOpenFoto.setToolTipText("Buscar foto");
        btnOpenFoto.setBackgroundHover(new java.awt.Color(57, 140, 136));
        btnOpenFoto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_OPEN);
        btnOpenFoto.setRound(5);
        btnOpenFoto.setSizeIcon(25.0F);
        btnOpenFoto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenFotoActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(btnOpenFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 75, 30));

        lblFoto.setBgBorder(new java.awt.Color(68, 165, 160));
        lblFoto.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hombre.png"))); // NOI18N
        lblFoto.setShapePanel(rojeru_san.efectos.ValoresEnum.PANEL_FORMA.CIRCLE);

        javax.swing.GroupLayout lblFotoLayout = new javax.swing.GroupLayout(lblFoto);
        lblFoto.setLayout(lblFotoLayout);
        lblFotoLayout.setHorizontalGroup(
            lblFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        lblFotoLayout.setVerticalGroup(
            lblFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        rSPanelBorder1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        rSPanelBorderGradient1.setBgShade(new java.awt.Color(68, 165, 160));
        rSPanelBorderGradient1.setColorPrimario(new java.awt.Color(68, 165, 160));
        rSPanelBorderGradient1.setColorSecundario(new java.awt.Color(26, 117, 159));

        btnCerrar.setBackground(new java.awt.Color(216, 43, 43));
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setBackgroundHover(new java.awt.Color(255, 51, 51));
        btnCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCerrar.setRound(50);
        btnCerrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Nuevo Medico");

        javax.swing.GroupLayout rSPanelBorderGradient1Layout = new javax.swing.GroupLayout(rSPanelBorderGradient1);
        rSPanelBorderGradient1.setLayout(rSPanelBorderGradient1Layout);
        rSPanelBorderGradient1Layout.setHorizontalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rSPanelBorderGradient1Layout.setVerticalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        rSPanelBorder1.add(rSPanelBorderGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 671, -1));

        btnRemove.setBackground(new java.awt.Color(102, 102, 102));
        btnRemove.setToolTipText("Remover foto");
        btnRemove.setBackgroundHover(new java.awt.Color(117, 116, 116));
        btnRemove.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RESTORE);
        btnRemove.setRound(5);
        btnRemove.setSizeIcon(25.0F);
        btnRemove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 75, 30));

        nombre.setForeground(new java.awt.Color(51, 51, 51));
        nombre.setBorderColor(new java.awt.Color(51, 51, 51));
        nombre.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nombre.setPhColor(new java.awt.Color(51, 51, 51));
        nombre.setPlaceholder("Nombre");
        nombre.setSelectionColor(new java.awt.Color(51, 51, 51));
        nombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreKeyTyped(evt);
            }
        });
        rSPanelBorder1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 300, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel2.setText("Nombre*");
        rSPanelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel3.setText("Apellido Paterno*");
        rSPanelBorder1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 330, -1));

        apellidoPaterno.setForeground(new java.awt.Color(51, 51, 51));
        apellidoPaterno.setBorderColor(new java.awt.Color(51, 51, 51));
        apellidoPaterno.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        apellidoPaterno.setPhColor(new java.awt.Color(51, 51, 51));
        apellidoPaterno.setPlaceholder("Apellido Paterno");
        apellidoPaterno.setSelectionColor(new java.awt.Color(51, 51, 51));
        apellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                apellidoPaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apellidoPaternoKeyTyped(evt);
            }
        });
        rSPanelBorder1.add(apellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 330, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel5.setText("Apellido Materno");
        rSPanelBorder1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 300, -1));

        apellidoMaterno.setForeground(new java.awt.Color(51, 51, 51));
        apellidoMaterno.setBorderColor(new java.awt.Color(51, 51, 51));
        apellidoMaterno.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        apellidoMaterno.setPhColor(new java.awt.Color(51, 51, 51));
        apellidoMaterno.setPlaceholder("Apellido Materno");
        apellidoMaterno.setSelectionColor(new java.awt.Color(51, 51, 51));
        apellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                apellidoMaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apellidoMaternoKeyTyped(evt);
            }
        });
        rSPanelBorder1.add(apellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel8.setText("Sexo*");
        rSPanelBorder1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 330, -1));

        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Sexo", "Hombre", "Mujer" }));
        sexo.setColorArrow(new java.awt.Color(68, 165, 160));
        sexo.setColorBorde(new java.awt.Color(68, 165, 160));
        sexo.setColorFondo(new java.awt.Color(68, 165, 160));
        sexo.setColorSeleccion(new java.awt.Color(68, 165, 160));
        sexo.setDisabledIdex("0");
        sexo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        sexo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sexoActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 330, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel7.setText("CURP");
        rSPanelBorder1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 300, -1));

        CURP.setForeground(new java.awt.Color(51, 51, 51));
        CURP.setBorderColor(new java.awt.Color(51, 51, 51));
        CURP.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        CURP.setPhColor(new java.awt.Color(51, 51, 51));
        CURP.setPlaceholder("Usuario");
        CURP.setSelectionColor(new java.awt.Color(51, 51, 51));
        CURP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                CURPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CURPKeyTyped(evt);
            }
        });
        rSPanelBorder1.add(CURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 300, -1));

        btnRegistrar.setBackground(new java.awt.Color(68, 165, 160));
        btnRegistrar.setText("Registar Usuario");
        btnRegistrar.setBackgroundHover(new java.awt.Color(57, 140, 136));
        btnRegistrar.setEnabled(false);
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);
        btnRegistrar.setRound(20);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        error_nombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        error_nombre.setText("Etiqueta de Error");
        rSPanelBorder1.add(error_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 300, -1));

        error_apellidoPaterno.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        error_apellidoPaterno.setText("Etiqueta de Error");
        rSPanelBorder1.add(error_apellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 330, -1));

        error_sexo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        error_sexo.setText("Etiqueta de Error");
        rSPanelBorder1.add(error_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 480, 330, -1));

        error_usuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        error_usuario.setText("Etiqueta de Error");
        rSPanelBorder1.add(error_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 300, -1));

        error_apellidoMaterno.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        error_apellidoMaterno.setText("Etiqueta de Error");
        rSPanelBorder1.add(error_apellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 480, 300, -1));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sexoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sexoActionPerformed
    {//GEN-HEADEREND:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarActionPerformed

        boolean sexoCorrect = MetodosAux.validarBox(sexo, error_sexo, "required");
        if (nombreC && apeP && apeM && sexoCorrect && curpC)
        {

            String rutaImgPerfilRegistro = null;

            rutaImgPerfilRegistro = (rutaImgPerfil != "") ? rutaImgPerfil : "./default/" + sexo.getSelectedItem().toString() + ".png";

            String apellidoMat = (!apellidoMaterno.getText().trim().equals("")) ? apellidoMaterno.getText().trim() : "No Proporcionado";

            Object[] datosInsert =
            {
                //Mandamos la informacion que puede contener vacio segun lo que se tenga almacenado en la caja de texto
                nombre.getText().trim(),
                apellidoPaterno.getText().trim(),
                apellidoMat,
                sexo.getSelectedItem().toString(),
                rutaImgPerfilRegistro,
                CURP.getText().trim()
            };

            boolean insercionCorr = MetodosBD.insertarMedico(datosInsert);
            if (insercionCorr)
            {
                MetodosAux.mostrarAlerta("Muy bien hecho", "Medico Registrado con Exito", 1);
                dispose();
                //Borramos la ruta de la imagen para refrescar
                rutaImgPerfilRegistro = null;
                //Actualizamos los usuariosd de las tablas
                TablaContenidoUsuarios.listarUsuarios(tablaContenidoUsuarios2.tblUsuario, tabSelecc, null);
                //Actualizamos el contador
                Usuarios.actualizarNumUsuarios();
            } else
            {
                MetodosAux.mostrarAlerta("Error", "Ocurro un error al insertar el Medico", 2);
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarActionPerformed
    {//GEN-HEADEREND:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyTyped
    {//GEN-HEADEREND:event_nombreKeyTyped
        if (nombre.getText().length() >= 25)
        {
            evt.consume();
        }
        setTransferHandler(null);
        Validaciones.entradaLetrasNum(evt, 1);
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoPaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoPaternoKeyTyped
    {//GEN-HEADEREND:event_apellidoPaternoKeyTyped
        if (apellidoPaterno.getText().length() >= 25)
        {
            evt.consume();
        }
        setTransferHandler(null);
        Validaciones.entradaLetrasNum(evt, 1);
    }//GEN-LAST:event_apellidoPaternoKeyTyped

    private void apellidoMaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoMaternoKeyTyped
    {//GEN-HEADEREND:event_apellidoMaternoKeyTyped
        if (apellidoMaterno.getText().length() >= 25)
        {
            evt.consume();
        }
        Validaciones.entradaLetrasNum(evt, 1);
    }//GEN-LAST:event_apellidoMaternoKeyTyped

    private void CURPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CURPKeyTyped
    {//GEN-HEADEREND:event_CURPKeyTyped
        if (CURP.getText().length() >= 40)
        {
            evt.consume();
        }
        setTransferHandler(null);
    }//GEN-LAST:event_CURPKeyTyped

    private void nombreKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyReleased
    {//GEN-HEADEREND:event_nombreKeyReleased
        nombreC = MetodosAux.validarFormu(nombre, error_nombre, "required");
        if (nombre.getText().length() <= 2 && !nombre.getText().isEmpty())
        {
            error_nombre.setForeground(SysConfigs.bg_warning);
            error_nombre.setText("Digite mas de 2 digitos");
            nombreC = false;
        }
        btnRegistrar.setEnabled((apeP == true && nombreC == true && curpC == true && (sexo.getSelectedIndex() == 1 || sexo.getSelectedIndex() == 2)) ? true : false);
    }//GEN-LAST:event_nombreKeyReleased

    private void apellidoPaternoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoPaternoKeyReleased
    {//GEN-HEADEREND:event_apellidoPaternoKeyReleased
        apeP = MetodosAux.validarFormu(apellidoPaterno, error_apellidoPaterno, "required");
        if (apellidoPaterno.getText().length() <= 2 && !apellidoPaterno.getText().isEmpty())
        {
            error_apellidoPaterno.setForeground(SysConfigs.bg_warning);
            error_apellidoPaterno.setText("Digite mas de 2 digitos");
            apeP = false;
        }
        btnRegistrar.setEnabled((apeP == true && nombreC == true && curpC == true && (sexo.getSelectedIndex() == 1 || sexo.getSelectedIndex() == 2)) ? true : false);
    }//GEN-LAST:event_apellidoPaternoKeyReleased

    private void apellidoMaternoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoMaternoKeyReleased
    {//GEN-HEADEREND:event_apellidoMaternoKeyReleased
        if (apellidoMaterno.getText().length() <= 2 && !apellidoMaterno.getText().isEmpty())
        {
            error_apellidoMaterno.setForeground(SysConfigs.bg_warning);
            error_apellidoMaterno.setText("Digite mas de 2 digitos");
            apeM = false;
        } else
        {
            if (apellidoMaterno.getText().isEmpty() || apellidoMaterno.getText().length() >= 3)
            {
                error_apellidoMaterno.setForeground(SysConfigs.bg_white);
                error_apellidoMaterno.setText("Error en el campo");
                apeM = true;
            }
        }
    }//GEN-LAST:event_apellidoMaternoKeyReleased

    private void btnOpenFotoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenFotoActionPerformed
    {//GEN-HEADEREND:event_btnOpenFotoActionPerformed
        rutaImgPerfil = MetodosAux.getFoto(this);
        if (!rutaImgPerfil.equals(""))
        {
            lblFoto.setImagen(new ImageIcon(rutaImgPerfil));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenFotoActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveActionPerformed
    {//GEN-HEADEREND:event_btnRemoveActionPerformed

        lblFoto.setImagen(null);
        rutaImgPerfil = "";
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void CURPKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CURPKeyReleased
    {//GEN-HEADEREND:event_CURPKeyReleased
        if (!CURP.getText().isEmpty() && MetodosBD.existeCampoRepet(CURP.getText().trim(), "usuario", "usuarios") == false)
        {
            curpC = true;
            error_usuario.setForeground(SysConfigs.bg_white);
            error_usuario.setText("Error de campo");
            btnRegistrar.setEnabled((apeP == true && nombreC == true && curpC == true && (sexo.getSelectedIndex() == 1 || sexo.getSelectedIndex() == 2)) ? true : false);
        } else
        {
            if (MetodosBD.existeCampoRepet(CURP.getText().trim(), "usuario", "usuarios") == true)
            {
                error_usuario.setForeground(SysConfigs.bg_danger);
                error_usuario.setText("Ops, este usuario ya exsite");
            }
        }
    }//GEN-LAST:event_CURPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new RegMedicos().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTextFieldOne CURP;
    private RSMaterialComponent.RSTextFieldOne apellidoMaterno;
    private RSMaterialComponent.RSTextFieldOne apellidoPaterno;
    private RSMaterialComponent.RSButtonIconOne btnCerrar;
    private RSMaterialComponent.RSButtonIconOne btnOpenFoto;
    private newscomponents.RSButtonIcon_new btnRegistrar;
    private RSMaterialComponent.RSButtonIconOne btnRemove;
    private javax.swing.JLabel error_apellidoMaterno;
    private javax.swing.JLabel error_apellidoPaterno;
    private javax.swing.JLabel error_nombre;
    private javax.swing.JLabel error_sexo;
    private javax.swing.JLabel error_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private RSMaterialComponent.RSPanelBorderImage lblFoto;
    private RSMaterialComponent.RSTextFieldOne nombre;
    private javax.swing.JPanel pnlFondo;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient1;
    private RSMaterialComponent.RSComboBox sexo;
    // End of variables declaration//GEN-END:variables
}
