/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alertas;

import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import metodosAux.RSObjectArray;
import metodosAux.SysConfigs;
import rojeru_san.complementos.RSEffectFade;
import rojeru_san.complementos.RSUtilities;
import rojeru_san.efectos.ValoresEnum;

/**
 *
 * @author Kevin
 */
public class Alerta extends java.awt.Dialog
{
    
    RSObjectArray arr = new RSObjectArray();

    /**
     * Creates new form Alerta
     * @param parent frame a mostrar
     * @param modal true
     * @param datos datos a mostrar en la alerta
     */
    public Alerta(java.awt.Frame parent, boolean modal, RSObjectArray datos)
    {
        super(parent, modal);
        initComponents();
        RSUtilities.setCenterWindow(this);
        RSEffectFade.setFadeWindowIn(this, 30, 0.3f);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);
        RSUtilities.setOpaqueWindow(this, false);
        this.arr = datos;
        titulo.setText(datos.getValue("titulo").toString());
        mensaje.setText(getHTML(datos.getValue("mensaje").toString()));
        
        switch (Integer.parseInt(datos.getValue("tipo").toString()))
        {
            case 1:
                circle.setForeground(SysConfigs.bg_success);
                check.setForeground(SysConfigs.bg_success);
                check.setIcons(ValoresEnum.ICONS.CHECK);
                pnlBorder.setBgBorder(SysConfigs.bg_success);
                btnAceptar.setBackground(SysConfigs.bg_success);
                break;
            
            case 2:
                circle.setForeground(SysConfigs.bg_danger);
                check.setForeground(SysConfigs.bg_danger);
                check.setIcons(ValoresEnum.ICONS.CLOSE);
                pnlBorder.setBgBorder(SysConfigs.bg_danger);
                btnAceptar.setBackground(SysConfigs.bg_danger);
                break;
            case 3:
                circle.setForeground(SysConfigs.bg_warning);
                check.setForeground(SysConfigs.bg_warning);
                check.setIcons(ValoresEnum.ICONS.WARNING);
                pnlBorder.setBgBorder(SysConfigs.bg_warning);
                btnAceptar.setBackground(SysConfigs.bg_warning);
                break;
            case 4:
                circle.setForeground(SysConfigs.bg_info);
                check.setForeground(SysConfigs.bg_info);
                check.setIcons(ValoresEnum.ICONS.INFO);
                pnlBorder.setBgBorder(SysConfigs.bg_info);
                btnAceptar.setBackground(SysConfigs.bg_info);
                break;
        }
    }
    
    public Alerta(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        RSUtilities.setCenterWindow(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);
        RSUtilities.setOpaqueWindow(this, false);
        
    }
    
    public String getHTML(String mensaje)
    {
        String html = "<html>\n"
                + "  <head>\n"
                + "\n"
                + "  </head>\n"
                + "  <body>\n"
                + "    <p style=\"margin-top:0;font-size:16px;color:black;text-align:center;font-family:georgia,garamond,serif;font-size:16px;font-style:italic;\">" + mensaje + "</p>\n"
                + "  </body>\n"
                + "</html>\n"
                + "";
        return html;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        pnlBorder = new RSMaterialComponent.RSPanelBorder();
        jPanel1 = new javax.swing.JPanel();
        check = new RSMaterialComponent.RSLabelIcon();
        circle = new RSMaterialComponent.RSLabelIcon();
        titulo = new javax.swing.JLabel();
        mensaje = new javax.swing.JEditorPane();
        btnAceptar = new newscomponents.RSButtonIcon_new();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setIntensity(10);
        rSPanelMaterial1.setRound(20);

        pnlBorder.setBackground(new java.awt.Color(255, 255, 255));
        pnlBorder.setRound(10);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        check.setForeground(new java.awt.Color(151, 194, 129));
        check.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);
        check.setSizeIcon(90.0F);

        circle.setForeground(new java.awt.Color(151, 194, 129));
        circle.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RADIO_BUTTON_UNCHECKED);
        circle.setSizeIcon(150.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(116, Short.MAX_VALUE)
                    .addComponent(circle, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(98, 98, 98)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(circle, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        titulo.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("jLabel1");

        mensaje.setEditable(false);
        mensaje.setContentType("text/html"); // NOI18N
        mensaje.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        mensaje.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top:0;font-size:16px;color:black;text-align:center;font-family:georgia,garamond,serif;font-size:16px;font-style:italic;\">\r\n      \r\n    </p>\r\n  </body>\r\n</html>\r\n");

        btnAceptar.setBackground(new java.awt.Color(51, 153, 0));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBackgroundHover(new java.awt.Color(151, 194, 129));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK_CIRCLE);
        btnAceptar.setRound(20);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBorderLayout = new javax.swing.GroupLayout(pnlBorder);
        pnlBorder.setLayout(pnlBorderLayout);
        pnlBorderLayout.setHorizontalGroup(
            pnlBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mensaje)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlBorderLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        pnlBorderLayout.setVerticalGroup(
            pnlBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Alerta dialog = new Alerta(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonIcon_new btnAceptar;
    private RSMaterialComponent.RSLabelIcon check;
    private RSMaterialComponent.RSLabelIcon circle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JEditorPane mensaje;
    private RSMaterialComponent.RSPanelBorder pnlBorder;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
