/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alertas;

import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import rojeru_san.complementos.RSEffectFade;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author Kevin
 */
public class Mensajes extends java.awt.Dialog
{

    /**
     * Creates new form Alerta
     * @param parent frame
     * @param modal true
     * @param mensaje mensaje que se mostrara en la alerta
     */
    public Mensajes(java.awt.Frame parent, boolean modal, String mensaje)
    {
        super(parent, modal);
        initComponents();
        RSUtilities.setCenterWindow(this);
        RSEffectFade.setFadeWindowIn(this, 30, 0.3f);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);
        RSUtilities.setOpaqueWindow(this, false);
        tmensaje.setText(getHTML(mensaje));
    }

    public Mensajes(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        RSUtilities.setCenterWindow(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);
        RSUtilities.setOpaqueWindow(this, false);
    }

    public String getHTML(String mensaje)
    {
        String html = "<html>\n"
                + "  <head>\n"
                + "\n"
                + "  </head>\n"
                + "  <body>\n"
                + "    <p style=\"margin-top:0;font-size:16px;color:black;text-align:center;font-family:georgia,garamond,serif;font-size:16px;font-style:italic;\">" + mensaje + "</p>\n"
                + "  </body>\n"
                + "</html>\n"
                + "";
        return html;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        pnlBorder = new RSMaterialComponent.RSPanelBorder();
        btnAceptar = new newscomponents.RSButtonIcon_new();
        tmensaje = new javax.swing.JEditorPane();
        circle = new RSMaterialComponent.RSLabelIcon();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setIntensity(10);
        rSPanelMaterial1.setRound(20);

        pnlBorder.setBackground(new java.awt.Color(255, 255, 255));
        pnlBorder.setRound(10);

        btnAceptar.setBackground(new java.awt.Color(150, 199, 126));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBackgroundHover(new java.awt.Color(151, 194, 129));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK_CIRCLE);
        btnAceptar.setRound(20);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        tmensaje.setEditable(false);
        tmensaje.setContentType("text/html"); // NOI18N
        tmensaje.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        tmensaje.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style = \"margin-top:0;font-size:16px;color:black;text-align:center;font-family:georgia,garamond,serif;font-size:16px;font-style:italic;\">\r\n      \r\n    </p>\r\n  </body>\r\n</html>\r\n");

        circle.setForeground(new java.awt.Color(153, 204, 255));
        circle.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ERROR_OUTLINE);
        circle.setSizeIcon(70.0F);

        javax.swing.GroupLayout pnlBorderLayout = new javax.swing.GroupLayout(pnlBorder);
        pnlBorder.setLayout(pnlBorderLayout);
        pnlBorderLayout.setHorizontalGroup(
            pnlBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(circle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(tmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        pnlBorderLayout.setVerticalGroup(
            pnlBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(circle, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(tmensaje))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Mensajes dialog = new Mensajes(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonIcon_new btnAceptar;
    private RSMaterialComponent.RSLabelIcon circle;
    private RSMaterialComponent.RSPanelBorder pnlBorder;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private javax.swing.JEditorPane tmensaje;
    // End of variables declaration//GEN-END:variables
}
