/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_Detalles;

import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import rojeru_san.complementos.RSUtilities;
import metodosAux.*;
import metodosBD.MetodosBD;
import static paneles.Servicios.actualizarNumServicios;
import static paneles.Servicios.tabSelecc;
import static paneles.Servicios.tablaContenidoServicios1;
import paneles.TablaContenidoServicios;
import rojeru_san.complementos.RSEffectFade;
import rojeru_san.efectos.ValoresEnum;

/**
 *
 * @author David Vergara
 */
public class InfoServicios extends javax.swing.JDialog
{

    RSObjectArray arregloDatos = new RSObjectArray();

    /**
     * Creates new form FormPacientes
     */
    public InfoServicios(java.awt.Frame parent, boolean modal, RSObjectArray datos)
    {
        super(parent, modal);
        this.arregloDatos = datos;
        //RSUtilities.setFullScreenJFrame(this);
        initComponents();
        RSEffectFade.setFadeWindowIn(this, 30, 0.3f);
        RSUtilities.setCenterWindow(this);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.pnlFondo, 150);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);

        lblNombre.setText(arregloDatos.getValue("nombreServ").toString());
        jTextArea1.setText(arregloDatos.getValue("descripcion").toString());
        lblUsuario.setText(arregloDatos.getValue("nombreUsr").toString());
        lblFecha.setText(arregloDatos.getValue("FechaReg").toString());
        lblEstatus.setText(arregloDatos.getValue("estatus").toString());
        lblEstatus.setForeground((arregloDatos.getValue("estatus").equals("Activo")) ? new Color(151, 194, 129) : new Color(216, 43, 43));
        rSLabelTextIcon6.setForeground((arregloDatos.getValue("estatus").equals("Activo")) ? new Color(151, 194, 129) : new Color(216, 43, 43));
        //Le ponemos el color al boton segun sea el caso del estatus
        btnEstatus.setBackground((arregloDatos.getValue("estatus").equals("Activo")) ? new Color(216, 43, 43) : new Color(151, 194, 129));
        btnEstatus.setBackgroundHover((arregloDatos.getValue("estatus").equals("Activo")) ? new Color(216, 43, 43) : new Color(151, 194, 129));
        //Le ponemos el texto al boton segun sea el caso del estatus
        btnEstatus.setText((arregloDatos.getValue("estatus").equals("Activo")) ? "Inhabilitar" : "Habilitar");
        btnEstatus.setIcons((arregloDatos.getValue("estatus").equals("Activo")) ? ValoresEnum.ICONS.RADIO_BUTTON_UNCHECKED : ValoresEnum.ICONS.RADIO_BUTTON_CHECKED);

    }

    public InfoServicios(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        RSEffectFade.setFadeWindowIn(this, 30, 0.3f);
        RSUtilities.setCenterWindow(this);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.pnlFondo, 150);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        setShape(forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlFondo = new javax.swing.JPanel();
        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        rSPanelBorderGradient1 = new RSMaterialComponent.RSPanelBorderGradient();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new RSMaterialComponent.RSButtonIconOne();
        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rSPanelBorder3 = new RSMaterialComponent.RSPanelBorder();
        rSLabelTextIcon9 = new RSMaterialComponent.RSLabelTextIcon();
        lblUsuario = new javax.swing.JLabel();
        rSPanelBorder2 = new RSMaterialComponent.RSPanelBorder();
        rSLabelTextIcon6 = new RSMaterialComponent.RSLabelTextIcon();
        lblEstatus = new javax.swing.JLabel();
        rSPanelBorder4 = new RSMaterialComponent.RSPanelBorder();
        rSLabelTextIcon8 = new RSMaterialComponent.RSLabelTextIcon();
        lblFecha = new javax.swing.JLabel();
        btnEstatus = new newscomponents.RSButtonIcon_new();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        pnlFondo.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(204, 182, 128));
        rSPanelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelBorderGradient1.setBgShade(new java.awt.Color(204, 182, 128));
        rSPanelBorderGradient1.setColorPrimario(new java.awt.Color(144, 224, 239));
        rSPanelBorderGradient1.setColorSecundario(new java.awt.Color(204, 182, 128));
        rSPanelBorderGradient1.setGradiente(RSMaterialComponent.RSPanelBorderGradient.Gradiente.CIRCULAR);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Información del Servicio");

        btnCerrar.setBackground(new java.awt.Color(216, 43, 43));
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setBackgroundHover(new java.awt.Color(255, 51, 51));
        btnCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnCerrar.setRound(50);
        btnCerrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelBorderGradient1Layout = new javax.swing.GroupLayout(rSPanelBorderGradient1);
        rSPanelBorderGradient1.setLayout(rSPanelBorderGradient1Layout);
        rSPanelBorderGradient1Layout.setHorizontalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rSPanelBorderGradient1Layout.setVerticalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        rSPanelBorder1.add(rSPanelBorderGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 110));

        lblNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        rSPanelBorder1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 440, 40));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 182, 128)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        rSPanelBorder1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 420, 110));

        rSPanelBorder3.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder3.setBgBorder(new java.awt.Color(204, 182, 128));

        rSLabelTextIcon9.setForeground(new java.awt.Color(51, 51, 51));
        rSLabelTextIcon9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSLabelTextIcon9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        rSLabelTextIcon9.setSizeIcon(30.0F);

        lblUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(153, 153, 153));
        lblUsuario.setText("Usuario");

        javax.swing.GroupLayout rSPanelBorder3Layout = new javax.swing.GroupLayout(rSPanelBorder3);
        rSPanelBorder3.setLayout(rSPanelBorder3Layout);
        rSPanelBorder3Layout.setHorizontalGroup(
            rSPanelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorder3Layout.setVerticalGroup(
            rSPanelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelTextIcon9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelBorder1.add(rSPanelBorder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 460, 60));

        rSPanelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder2.setBgBorder(new java.awt.Color(204, 182, 128));
        rSPanelBorder2.setBorderTop(false);

        rSLabelTextIcon6.setForeground(new java.awt.Color(51, 51, 51));
        rSLabelTextIcon6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSLabelTextIcon6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RADIO_BUTTON_CHECKED);
        rSLabelTextIcon6.setSizeIcon(30.0F);

        lblEstatus.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblEstatus.setForeground(new java.awt.Color(153, 153, 153));
        lblEstatus.setText("Estatus");

        javax.swing.GroupLayout rSPanelBorder2Layout = new javax.swing.GroupLayout(rSPanelBorder2);
        rSPanelBorder2.setLayout(rSPanelBorder2Layout);
        rSPanelBorder2Layout.setHorizontalGroup(
            rSPanelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorder2Layout.setVerticalGroup(
            rSPanelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder2Layout.createSequentialGroup()
                .addGroup(rSPanelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelTextIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelBorder1.add(rSPanelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 460, 50));

        rSPanelBorder4.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder4.setBgBorder(new java.awt.Color(204, 182, 128));
        rSPanelBorder4.setBorderTop(false);

        rSLabelTextIcon8.setForeground(new java.awt.Color(51, 51, 51));
        rSLabelTextIcon8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelTextIcon8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSLabelTextIcon8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        rSLabelTextIcon8.setSizeIcon(30.0F);

        lblFecha.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(153, 153, 153));
        lblFecha.setText("Fecha");

        javax.swing.GroupLayout rSPanelBorder4Layout = new javax.swing.GroupLayout(rSPanelBorder4);
        rSPanelBorder4.setLayout(rSPanelBorder4Layout);
        rSPanelBorder4Layout.setHorizontalGroup(
            rSPanelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorder4Layout.setVerticalGroup(
            rSPanelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelTextIcon8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelBorder1.add(rSPanelBorder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 460, 60));

        btnEstatus.setBackground(new java.awt.Color(216, 43, 43));
        btnEstatus.setText("Inhabilitar");
        btnEstatus.setBackgroundHover(new java.awt.Color(255, 51, 51));
        btnEstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEstatus.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEstatus.setRound(20);
        btnEstatus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEstatusActionPerformed(evt);
            }
        });
        rSPanelBorder1.add(btnEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 119, 41));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstatusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEstatusActionPerformed
    {//GEN-HEADEREND:event_btnEstatusActionPerformed

        int newEstatus = (arregloDatos.getValue("estatus").equals("Activo") ? 2 : 1);
        boolean resultado = MetodosBD.actualizarEstatusServicio((int) arregloDatos.getValue("id"), newEstatus);
        if (resultado)
        {
            dispose();
            TablaContenidoServicios.listarServicios(tablaContenidoServicios1.tblServicios, tabSelecc, null);
            actualizarNumServicios();
            if (newEstatus == 1)
            {
                MetodosAux.mostrarAlerta("Muy bien hecho", "Servicio Activado con Exito", 1);
            } else
            {
                if (newEstatus == 2)
                {
                    MetodosAux.mostrarAlerta("Muy bien hecho", "Servicio Desactivado con Exito", 1);
                } else
                {
                    MetodosAux.mostrarAlerta("Error", "No se pudo completar la acción", 2);
                }

            }
        }

    }//GEN-LAST:event_btnEstatusActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarActionPerformed
    {//GEN-HEADEREND:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InfoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InfoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InfoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InfoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                InfoServicios dialog = new InfoServicios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnCerrar;
    private newscomponents.RSButtonIcon_new btnEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFondo;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon6;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon8;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon9;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder2;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder3;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder4;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient1;
    // End of variables declaration//GEN-END:variables
}
